---
swagger: '2.0'
info:
  description: Documentasi API Service Klik-Pasien For RS Data Master
  version: '1.0'
  title: API Service KLIKMEDIC
host: petstore.swagger.io
schemes:
- http
- https
paths:
  "/pasien":
    post:
      summary: Create Data Pasien
      tags:
      - Pasien
      operationId: CreatedPasien
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          "$ref": "#/definitions/CreatePasien"
      responses:
        '200':
          description: ''
          headers: {}
definitions:
  CreatePasien:
    title: Pasien
    example:
      nama: "KHAIRIL ANWAR"
      no_mr: "001234"
      no_mr_lama: "-"
      nik: '1272072906910002'
      no_kk: "-"
      jenis_kelamin: 1
      tanggal_lahir: '1991-06-29 17:00:00'
      tempat_lahir: Tapaktuan
      gol_darah: O
      suku: GORONTALO
      bahasa: INDONESIA
      id_prov: 75
      id_kabkota: 7502
      id_kecamatan: 750211
      id_desa: 750238827
      alamat: "Jl. Arif Rahman Hakim"
      kdpos: 86524
      negara: INDONESIA
      id_provd: 75
      id_kabkotad: 7502
      id_kecamatand: 750211
      id_desad: 750238827
      alamatd: "Jl. Arif Rahman Hakim"
      kdposd: 86524
      negarad: INDONESIA
      tlp_rumah: "+620435787878"
      id_jpdd: S1
      id_pekerjaan: 1022
      no_hp: "+6282290012005"
      email: zulfahmii051@gmail.com
      nama_ibu: "WARNI BILONDATU"
    type: object
    properties:
      nik:
        type: string
      no_kk:
        type: string
      nama:
        type: string
      jenis_kelamin:
        type: integer
        format: int32
      tanggal_lahir:
        type: string
      tempat_lahir:
        type: string
      gol_darah:
        type: string
      provinsi:
        "$ref": "#/definitions/Provinsi"
      kabupaten:
        "$ref": "#/definitions/Kabupaten"
      kecamatan:
        "$ref": "#/definitions/Kecamatan"
      desa:
        "$ref": "#/definitions/Desa"
      alamat:
        type: string
      no_hp:
        type: string
      email:
        type: string
    required:
    - nama
    - nik
    - no_kk
    - jenis_kelamin
    - tanggal_lahir
    - tempat_lahir
    - gol_darah
    - provinsi
    - kabupaten
    - kecamatan
    - desa
    - alamat
    - no_hp
    - email
  Provinsi:
    title: Provinsi
    example:
      kode: 11
      nama: ACEH
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  Kabupaten:
    title: Kabupaten
    example:
      kode: 1112
      nama: ACEH BARAT DAYA
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  Kecamatan:
    title: Kecamatan
    example:
      kode: 111204
      nama: SUSOH
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  Desa:
    title: Desa
    example:
      kode: 111204007
      nama: RUMAH DUA LAPIS
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
security:
- bearer: []
tags:
- name: Pasien
