---
swagger: '2.0'
info:
  description: Documentasi API Service Klik-Pasien For RS Data Master
  version: '1.0'
  title: API Service KLIKMEDIC
host: petstore.swagger.io
schemes:
- http
- https
paths:
  "/Pasien":
    post:
      summary: Create Data Pasien
      tags:
      - Pasien
      operationId: CreatedPasien
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          "$ref": "#/definitions/CreatePasien"
      responses:
        '200':
          description: ''
          headers: {

          }

  Pasien/get:
    get:
        tags:
          - Pasien
        summary: Finds Patient by status
        description: Multiple status values can be provided with comma separated strings
        operationId: findPatientByStatus
        parameters:
          - name: status
            in: query
            description: Status values that need to be considered for filter
            required: false
            explode: true
            schema:
              type: string
              default: available
              enum:
                - available
                - pending
                - sold
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref": "#/definitions/CreatePasien"          
              application/xml:
                schema:
                  type: array
                  items:
                    "$ref": "#/definitions/CreatePasien"
          '400':
            description: Invalid status value
        security:
          - petstore_auth:
              - write:pets
              - read:pets
  "/Pasien/{id_user}":
    put:
      tags:
        - Pasien
      summary: Update an existing Patient
      description: Update an existing Patien by Id
      operationId: updatePet
      requestBody:
        description: Update an existent Patien in the store
        content:
          application/json:
            schema:
              "$ref": "#/definitions/CreatePasien"
          application/xml:
            schema:
              "$ref": "#/definitions/CreatePasien"
          application/x-www-form-urlencoded:
            schema:
              "$ref": "#/definitions/CreatePasien"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/definitions/CreatePasien"          
            application/xml:
              schema:
                "$ref": "#/definitions/CreatePasien"
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
definitions:
  CreatePasien:
    title: Pasien
    example:
      id_user: 1120120488
      id_finger: 
      foto: 
      tanda_tangan: 
      no_mr: 112233
      no_mr_lama: 111122
      kode_dpjp:
      gelar_dpn:
      nama_user: KHAIRIL ANWAR
      gelar_blk: S.Kom
      id_shift:
      tmp_lhr: GORONTALO
      tgl_lhr: 1980-12-29
      id_jk: 1
      id_kawin: 1
      id_agama: 1
      gol_darah: O
      berat_lahir: 
      id_jpdd: 1
      id_prodi: 1
      id_pekerjaan: 1
      id_pekerjaan_sts: 
      id_kantor: 
      id_grupsdm: 
      tarif_konsul: 
      sts_tarif_dikelola_dokter: 
      ket_spesialisasi: 
      no_sip: 
      id_ruangan: 
      tmt_cpns: 
      tmt_pns: 
      nip: 
      no_karpeg: 
      npwp: 
      jenis_identitas: 1
      no_identitas: 7502046602070001
      no_kk: 750360111222244
      no_hp: +6282349782444
      email: khairilanwarkarim@gmail.com
      grup_user: 1
      sts_user: 1
      sts_difabel: 
      sts_prioritas: 
      id_prov: 75
      id_kabkota: 7502
      id_kecamatan: 750211
      id_desa: 750238827
      alamat: "Jl. Arif Rahman Hakim"
      kdpos: 86524
      negara: INDONESIA
      id_provd: 75
      id_kabkotad: 7502
      id_kecamatand: 750211
      id_desad: 750238827
      alamatd: "Jl. Arif Rahman Hakim"
      kdposd: 86524
      negarad: INDONESIA
      tlp_rumah: "+620435787878"
      nama_ibu: "WARNI BILONDATU"
      id_kelp_sdm: 
      nip_lama: 
      cuti_tahunan:
      tmt_pensiun: 
      sts_allowed_credit: 
      riwayat_alergi_obat: 
      riwayat_alergi_makanan: 
      idcardprinted: 
      idcardtaked: 
      idcardpaid: 
      idcardexpired: 
      date_registered: 
      user_registered: 
      date_modified: 
      user_modified: 
      isdefault: 
      password:
      sts_update: 
    type: object
    properties:
      nama:
        type: string
      no_mr:
        type: string
      no_mr_lama:
        type: string
      nik:
        type: string
      no_kk: 
        type: string
      id_agama:
        "$ref": "#/definitions/Agama"
      jenis_kelamin: 
        type: integer
      tanggal_lahir:
        type: string
      tempat_lahir:
        type: string
      gol_darah:
        type: string
      suku: 
        type: string
      bahasa: 
        type: string
      id_prov:
        "$ref": "#/definitions/Provinsi"
      id_kabkota:
        "$ref": "#/definitions/Kabupaten"
      id_kecamatan:
        "$ref": "#/definitions/Kecamatan"
      id_desa:
        "$ref": "#/definitions/Desa"
      alamat:
        type: string
      kdpos:
        type: string
      negara:
        type: string
      id_provd:
         "$ref": "#/definitions/Provinsi"
      id_kabkotad:
        "$ref": "#/definitions/Kabupaten"
      id_kecamatand:
        "$ref": "#/definitions/Kecamatan"
      id_desad:
        "$ref": "#/definitions/Desa"
      alamatd:
        type: string
      kdposd:
        type: string
      negarad:
        type: string
      tlp_rumah:
        type: string
      id_jpdd:
        "$ref": "#/definitions/jpdd"
      id_pekerjaan:
        "$ref": "#/definitions/pekerjaan"
      no_hp:
        type: string
      email: 
        type: string
      nama_ibu: 
        type: string
    required:
    - nama
    - nik
    - no_kk
    - jenis_kelamin
    - tanggal_lahir
    - tempat_lahir
    - gol_darah
    - provinsi
    - kabupaten
    - kecamatan
    - desa
    - alamat
    - no_hp
    - email
  Agama:
    title: Agama
    example:
      id_agama: 1
      ket_agama: Islam
    type: object
    properties:
      id_agama:
        type: integer
        format: int32
      ket_agama:
        type: string
    required:
    - kode
    - nama  
  Provinsi:
    title: Provinsi
    example:
      kode: 11
      nama: ACEH
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  Kabupaten:
    title: Kabupaten
    example:
      kode: 1112
      nama: ACEH BARAT DAYA
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  Kecamatan:
    title: Kecamatan
    example:
      kode: 111204
      nama: SUSOH
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  Desa:
    title: Desa
    example:
      kode: 111204007
      nama: RUMAH DUA LAPIS
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  jpdd:
    title: Jpdd
    example:
      kode: 11
      nama: SD
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
  pekerjaan:
    title: Pekerjaan
    example:
      kode: 11
      nama: Wiraswasta
    type: object
    properties:
      kode:
        type: integer
        format: int32
      nama:
        type: string
    required:
    - kode
    - nama
security:
- bearer: []
tags:
- name: Pasien
